export const queryKeys = {
  me: ["me"] as const,
  dashboardStats: ["dashboard-stats"] as const,
  recentSubmissions: ["recent-submissions"] as const,
  attendanceToday: ["attendance-today"] as const,
  missingToday: ["missing-today"] as const,
  siteWiseStats: ["site-wise-stats"] as const,
  users: (params?: Record<string, unknown>) => ["users", params] as const,
  user: (id: string) => ["user", id] as const,
  sites: (params?: Record<string, unknown>) => ["sites", params] as const,
  site: (id: string) => ["site", id] as const,
  parameters: (siteId: string) => ["parameters", siteId] as const,
  assignments: (siteId: string) => ["assignments", siteId] as const,
  submissions: (params?: Record<string, unknown>) => ["submissions", params] as const,
  missingSubmissions: (date?: string) => ["missing-submissions", date] as const,
  attendance: (params?: Record<string, unknown>) => ["attendance", params] as const,
  attendanceSummary: (params?: Record<string, unknown>) => ["attendance-summary", params] as const,
  settings: ["settings"] as const,
};
